---
- name: Print system arch of nodes.
  hosts: all
  become: true
  tasks:
    - name: Store systems arch.
      command: uname -m
      register: abc
    - name: Print arch details
      debug:
        var: abc.stdout
    - name: Save the arch deatils on target nodes.
      copy:
        content: "{{ abc.stdout }} is the systems architecture."
        dest: /tmp/arch.txt
...
