---
- name: Install httpd
  hosts: test
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: "{{ ansible_facts['ansible_local']['httpd']['basic']['package'] }}"
        state: installed
    - name: Start and enable httpd service
      service:
           name: "{{ ansible_facts['ansible_local']['httpd']['basic']['service'] }}"
           state: "{{ ansible_facts['ansible_local']['httpd']['basic']['state'] }}"
           enabled: "{{ ansible_facts['ansible_local']['httpd']['basic']['enabled'] }}"
...
