---
- name: Ansible facts
  hosts: all
  become: true
  tasks:
    - name: Capture Kernel version
      copy:
        content: "The kernel version is {{ ansible_kernel }}"
        dest: /tmp/kernel.txt
...
