---
- name: Simulate a task to fail on a host.
  hosts: all
  become: true
  ignore_errors: yes
  tasks:
    - name: Set a task to fail.
      shell: cd /roott
    - name: Set a task to run successfully.
      shell: /bin/true
      notify: success
  handlers:
    - name: success
      debug:
        msg: "This task has been executed successfully."
...
