---
- name: Install apache web server.
  hosts: all
  become: true
  tasks:
    - name: Install the latest version of apache.
      yum:
        name: httpd
        state: latest
    - name: Configure apache
      copy:
        content: "Hello World."
        dest: /var/www/html/index.html
        owner: pen
        group: pen
        mode: 0644
      notify:
        - Start Apache
        - Configure Firewall
  handlers:
    - name: Start Apache
      service:
        name: httpd
        state: started
    - name: Configure Firewall
      firewalld:
        permanent: yes
        immediate: yes
        service: http
        state: enabled
...
