---
- name: Ansible playbook for making an entry in /etc/fstab file.
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Append the IP address and hostname information.
      lineinfile:
        line: "{{ ansible_default_ipv4.address }} {{ ansible_nodename }} {{ ansible_hostname }}"
        dest: /etc/hosts
...
