---
- name: Managing the file permission using ansible.
  hosts: all
  become: true
  tasks:
    - name: Change the access time of a file.
      file:
        path: /etc/linux.conf
        state: file
        access_time: "202011121015.0"
...
