---
- name: Managing the file permission using ansible.
  hosts: all
  become: true
  tasks:
    - name: Update access and modification time of given file.
      file:
        path: /etc/linux
        state: directory
        modification_time: now
        access_time: now
...
