---
- name: Managing the file permission using ansible.
  hosts: all
  become: true
  tasks:
    - name: touch again the same file, but do not change times this makes the task idempotent.
      file:
        path: /etc/linux.conf
        state: touch
        mode: u+rw,g+r,o+r
        modification_time: preserve
        access_time: preserve
...
