---
- name: Change Selinux mode in configuration file.
  become: true
  hosts: all
  tasks:
    - name: Change Selinux mode in /etc/selinux/config file.
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=enforcing'
...
