---
- name: Managing Storage Space using Ansible.
  hosts: test
  become: true
  tasks:
    - name: Create a new primary partition with size of 1GiB.
      parted:
        device: /dev/xvdb
        number: 1
        state: present
        part_end: 1GiB
...
