---
- name: Condition playbook example.
  hosts: all
  become: true
  tasks:
    - name: Install ftp package if OS is RHEL and its version is 9.
      yum:
        name: ftp
        state: installed
      when:
        - ansible_distribution == "RedHat" and ansible_distribution_major_version == "9"
...

