---
- name: Yum repository management.
  hosts: test
  become: true
  tasks:
    - name: Add repository.
      yum_repository:
        name: epel
        description: EPEL Yum repo
        baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        enabled: true
        gpgcheck: false
...
